### ISSUE TITLE
NPE sometimes when playing a newly created Sound

### ISSUE THREAD

**Issue by BambooBandit** [rafaskb/Boom#13]
Tested on libGDX versions 1.9.9 and 1.9.6, with Java 8 on Windows 10.

If you were to keep playing newly created sounds, such as:

```
public class EmptyTest extends Game
{
	Boom boom;
	BoomChannel boomChannel;
	@Override
	public void create () {
		boom = Boom.init();
		boomChannel = boom.createChannel(1);
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		if(Gdx.input.isKeyPressed(Input.Keys.SPACE))
		{
			boom.play(Gdx.audio.newSound(Gdx.files.internal("explosion.ogg")), boomChannel,.015f);
			boom.play(Gdx.audio.newSound(Gdx.files.internal("spark.ogg")), boomChannel,.015f);
			boom.play(Gdx.audio.newSound(Gdx.files.internal("explosion.ogg")), boomChannel,.015f);
			boom.play(Gdx.audio.newSound(Gdx.files.internal("spark.ogg")), boomChannel,.015f);
			boom.play(Gdx.audio.newSound(Gdx.files.internal("explosion.ogg")), boomChannel,.015f);
			boom.play(Gdx.audio.newSound(Gdx.files.internal("spark.ogg")), boomChannel,.015f);
		}
		super.render();
	}

	@Override
	public void dispose () {
	}
}
```

Hold space and randomly, you'll get this error.

```
Boom: Initializing Boom.
Exception in thread "main" java.lang.NullPointerException
	at lwjgl3.src.main.java.com.rafaskoberg.boom.BoomLwjgl3.play(BoomLwjgl3.java:98)
	at core.src.main.java.com.rafaskoberg.boom.Boom.play(Boom.java:62)
	at com.mygdx.emptytest.EmptyTest.render(EmptyTest.java:38)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:386)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	at com.mygdx.emptytest.desktop.DesktopLauncher.main(DesktopLauncher.java:15)
```

**Comment by BambooBandit** [comment]
It seems to still be happening in my game even when I create and cache the sounds before playing them.
